### ISSUE TITLE
spec/jsonapi/record_included_spec.rb:32 is failing on Ruby 2.5.1

### ISSUE THREAD

**Issue by HallDJack** [PopularPays/jsonapi-matchers#17]
The spec `spec/jsonapi/record_included_spec.rb:32` fails consistently on Ruby v2.5.1. The "invalid json" value used in the test is no longer raising an error.

**Comment by bauerjon** [comment]
Thanks @HallDJack! We will try and look into this soon. in the mean time if you want to submit a p.r. feel free and I can merge it in.

**Comment by HallDJack** [comment]
I am currently running Ruby v2.5.1, so this is no longer an issue.
