### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HallDJack** [PopularPays/jsonapi-matchers#23]
What are people's thoughts on adding version tags when changes are made. It would still be possible to install from master, but I would find it easier to remember which version I have installed if I was referencing a specific tag vs. having to look at the SHAs on master.

Tagging releases would require us to document the process (MVP should just be adding a git tag.) but I don't think the process would be too involved.

I don't think we would need to try and back date versions. We could just declare this is v1.0.0 (or whatever) and start from there. _We are currently at 0.1.0 in version.rb_

**Comment by bauerjon** [comment]
I like it! Haven't run into issues with shas personally but understand the desire for them and we could put on rubygems as well

**Comment by HallDJack** [comment]
This was resolved with https://github.com/PopularPays/jsonapi-matchers/pull/24.

V1.0.0 is released!
